volumes:
  mongo-db-volume:
    external: true
  postgres-db-volume:
    external: true

services:
  # BASE DE DATOS
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: 'mongo:6.0'
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    restart: always

  postgres-db:
    container_name: ${POSTGRES_DB}
    image: 'postgres:16-alpine'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always